# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shareif' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shareif

end

target 'ShareifS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareifS

end
